### ISSUE TITLE
Using @:extern typedef includes header without generating one

### ISSUE THREAD

**Issue by fourst4r** [RobertBorghese/reflaxe.CPP#13]
Building the following code:
```cpp
// Other.hx
@:extern typedef NewInt = Int;
```
```cpp
// Main.hx
function main() {
    var i:NewInt = 0;
    trace(i); // bypass dce
}
```
Will generate C++ that includes a `#include "Other.h"` but will not generate this file, causing C++ a compile error.

Love this library by the way. 😁

**Comment by RobertBorghese** [comment]
Oooo, biiiig find!! Thanks for the report, I'll fix asap! 👌 

I'm glad you like! Happy I'm not the only one using this ^^

**Comment by RobertBorghese** [comment]
All right, should be fixed! Run `haxelib update` and let me how it goes!

**Comment by fourst4r** [comment]
Works perfectly now. Thank you for the lightning fast response!
