### ISSUE TITLE
namespace wrong 

### ISSUE THREAD

**Issue by sonygod** [RobertBorghese/reflaxe.CPP#24]
```haxe
package cxx.std.chrono;

import cxx.Auto;



@:cxxStd
@:cppStd
@:nativeName("steady_clock")
@:include("chrono",true)
@:valueType
extern class SteadyClock {
	public static function now(): IAuto;

	
```

will generate

```cpp
auto now = cxx::std::chrono::steady_clock::now();  //cxx:: wrong!

//should be

auto now =std::chrono::steady_clock::now(); 



```

**Comment by RobertBorghese** [comment]
In this case, you probably want to use `@:native` or `@:nativeTypeCode`. 

`@:nativeName` was a meta I specifically added to retain the Haxe namespaces. But if you use `@:native("std::chrono::steady_clock")`, that should do the trick! 

You can also use `@:nativeTypeCode` to inject type arguments, check out:
https://github.com/RobertBorghese/reflaxe.CPP/blob/main/std/cxx/std/chrono/TimePoint.hx

**Comment by sonygod** [comment]
yeah. 

```hx
package cxx.std.chrono;

import cxx.Auto;



@:cxxStd
@:cppStd
@:native("std::chrono::steady_clock")
@:include("chrono",true)
@:valueType
extern class SteadyClock {
	public static function now(): IAuto;

	
}
```
