### ISSUE TITLE
Single Type is not supported

### ISSUE THREAD

**Issue by onehundredfeet** [RobertBorghese/reflaxe.CPP#6]
Type not found : Single

Single should be a 32-bit floating point number.

**Comment by onehundredfeet** [comment]
Wait.  It might be me.

**Comment by onehundredfeet** [comment]
Nope, it seems to not be supported broadly.

To try to fix it, I used 

```haxe
typedef Single=ucpp.num.Float32;
```

but it seems to lack a lot of the auto type conversion / comparison that the default types have.

**Comment by RobertBorghese** [comment]
Yeahhh, there's still some API types I'm missing here and there (^_^;)

Thanks for the feedback, and I'll fix this as soon as I can!

**Comment by RobertBorghese** [comment]
Ahhhh, I was confused cause I already had Single handled, but as it turns out, the Haxe API uses conditional compilation around Single so it doesn't appear on custom targets. I'll have to make a pr, but in meantime this should work. 👌
